// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: event.proto

package event

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VictoryType 胜利类型枚举
// 定义不同的获胜情况及对应的升级数
type VictoryType int32

const (
	// 未指定（默认值）
	VictoryType_VICTORY_TYPE_UNSPECIFIED VictoryType = 0
	// 双下：同队1、2名（升3级）
	VictoryType_VICTORY_TYPE_DOUBLE_DOWN VictoryType = 1
	// 单下：同队1、3名（升2级）
	VictoryType_VICTORY_TYPE_SINGLE_LAST VictoryType = 2
	// 末游：同队1、4名（升1级）
	VictoryType_VICTORY_TYPE_PARTNER_LAST VictoryType = 3
)

// Enum value maps for VictoryType.
var (
	VictoryType_name = map[int32]string{
		0: "VICTORY_TYPE_UNSPECIFIED",
		1: "VICTORY_TYPE_DOUBLE_DOWN",
		2: "VICTORY_TYPE_SINGLE_LAST",
		3: "VICTORY_TYPE_PARTNER_LAST",
	}
	VictoryType_value = map[string]int32{
		"VICTORY_TYPE_UNSPECIFIED":  0,
		"VICTORY_TYPE_DOUBLE_DOWN":  1,
		"VICTORY_TYPE_SINGLE_LAST":  2,
		"VICTORY_TYPE_PARTNER_LAST": 3,
	}
)

func (x VictoryType) Enum() *VictoryType {
	p := new(VictoryType)
	*p = x
	return p
}

func (x VictoryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VictoryType) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[0].Descriptor()
}

func (VictoryType) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[0]
}

func (x VictoryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VictoryType.Descriptor instead.
func (VictoryType) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

// EventType 游戏事件类型枚举
// 用于快速识别事件类型，无需检查 payload
type EventType int32

const (
	// 未指定（默认值）
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	// 比赛级事件
	EventType_EVENT_TYPE_MATCH_STARTED EventType = 1
	EventType_EVENT_TYPE_MATCH_ENDED   EventType = 2
	// 局级事件
	EventType_EVENT_TYPE_DEAL_STARTED EventType = 10
	EventType_EVENT_TYPE_CARDS_DEALT  EventType = 11
	EventType_EVENT_TYPE_DEAL_ENDED   EventType = 12
	// 进贡阶段事件
	EventType_EVENT_TYPE_TRIBUTE_STARTED        EventType = 20
	EventType_EVENT_TYPE_TRIBUTE_EXEMPTED       EventType = 21
	EventType_EVENT_TYPE_TRIBUTE_CARD_SUBMITTED EventType = 22
	EventType_EVENT_TYPE_TRIBUTE_CARD_SELECTED  EventType = 23
	EventType_EVENT_TYPE_TRIBUTE_CARD_RETURNED  EventType = 24
	EventType_EVENT_TYPE_TRIBUTE_COMPLETED      EventType = 25
	// 轮次级事件
	EventType_EVENT_TYPE_TRICK_STARTED EventType = 30
	EventType_EVENT_TYPE_TRICK_ENDED   EventType = 31
	// 玩家行为事件
	EventType_EVENT_TYPE_PLAYER_PLAYED     EventType = 40
	EventType_EVENT_TYPE_PLAYER_PASSED     EventType = 41
	EventType_EVENT_TYPE_PLAYER_TIMEOUT    EventType = 42
	EventType_EVENT_TYPE_PLAYER_DISCONNECT EventType = 43
	EventType_EVENT_TYPE_PLAYER_RECONNECT  EventType = 44
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EVENT_TYPE_UNSPECIFIED",
		1:  "EVENT_TYPE_MATCH_STARTED",
		2:  "EVENT_TYPE_MATCH_ENDED",
		10: "EVENT_TYPE_DEAL_STARTED",
		11: "EVENT_TYPE_CARDS_DEALT",
		12: "EVENT_TYPE_DEAL_ENDED",
		20: "EVENT_TYPE_TRIBUTE_STARTED",
		21: "EVENT_TYPE_TRIBUTE_EXEMPTED",
		22: "EVENT_TYPE_TRIBUTE_CARD_SUBMITTED",
		23: "EVENT_TYPE_TRIBUTE_CARD_SELECTED",
		24: "EVENT_TYPE_TRIBUTE_CARD_RETURNED",
		25: "EVENT_TYPE_TRIBUTE_COMPLETED",
		30: "EVENT_TYPE_TRICK_STARTED",
		31: "EVENT_TYPE_TRICK_ENDED",
		40: "EVENT_TYPE_PLAYER_PLAYED",
		41: "EVENT_TYPE_PLAYER_PASSED",
		42: "EVENT_TYPE_PLAYER_TIMEOUT",
		43: "EVENT_TYPE_PLAYER_DISCONNECT",
		44: "EVENT_TYPE_PLAYER_RECONNECT",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":            0,
		"EVENT_TYPE_MATCH_STARTED":          1,
		"EVENT_TYPE_MATCH_ENDED":            2,
		"EVENT_TYPE_DEAL_STARTED":           10,
		"EVENT_TYPE_CARDS_DEALT":            11,
		"EVENT_TYPE_DEAL_ENDED":             12,
		"EVENT_TYPE_TRIBUTE_STARTED":        20,
		"EVENT_TYPE_TRIBUTE_EXEMPTED":       21,
		"EVENT_TYPE_TRIBUTE_CARD_SUBMITTED": 22,
		"EVENT_TYPE_TRIBUTE_CARD_SELECTED":  23,
		"EVENT_TYPE_TRIBUTE_CARD_RETURNED":  24,
		"EVENT_TYPE_TRIBUTE_COMPLETED":      25,
		"EVENT_TYPE_TRICK_STARTED":          30,
		"EVENT_TYPE_TRICK_ENDED":            31,
		"EVENT_TYPE_PLAYER_PLAYED":          40,
		"EVENT_TYPE_PLAYER_PASSED":          41,
		"EVENT_TYPE_PLAYER_TIMEOUT":         42,
		"EVENT_TYPE_PLAYER_DISCONNECT":      43,
		"EVENT_TYPE_PLAYER_RECONNECT":       44,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[1].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[1]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

type TributeType int32

const (
	TributeType_TRIBUTE_TYPE_UNSPECIFIED  TributeType = 0
	TributeType_TRIBUTE_TYPE_DOUBLE_DOWN  TributeType = 1
	TributeType_TRIBUTE_TYPE_SINGLE_LAST  TributeType = 2
	TributeType_TRIBUTE_TYPE_PARTNER_LAST TributeType = 3
	TributeType_TRIBUTE_TYPE_NONE         TributeType = 4
)

// Enum value maps for TributeType.
var (
	TributeType_name = map[int32]string{
		0: "TRIBUTE_TYPE_UNSPECIFIED",
		1: "TRIBUTE_TYPE_DOUBLE_DOWN",
		2: "TRIBUTE_TYPE_SINGLE_LAST",
		3: "TRIBUTE_TYPE_PARTNER_LAST",
		4: "TRIBUTE_TYPE_NONE",
	}
	TributeType_value = map[string]int32{
		"TRIBUTE_TYPE_UNSPECIFIED":  0,
		"TRIBUTE_TYPE_DOUBLE_DOWN":  1,
		"TRIBUTE_TYPE_SINGLE_LAST":  2,
		"TRIBUTE_TYPE_PARTNER_LAST": 3,
		"TRIBUTE_TYPE_NONE":         4,
	}
)

func (x TributeType) Enum() *TributeType {
	p := new(TributeType)
	*p = x
	return p
}

func (x TributeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TributeType) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[2].Descriptor()
}

func (TributeType) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[2]
}

func (x TributeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TributeType.Descriptor instead.
func (TributeType) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

// PlayerTimeoutPayload 玩家超时事件数据
type PlayerTimeoutActionType int32

const (
	PlayerTimeoutActionType_PLAYER_TIMEOUT_ACTION_UNSPECIFIED    PlayerTimeoutActionType = 0
	PlayerTimeoutActionType_PLAYER_TIMEOUT_ACTION_PLAY_DECISION  PlayerTimeoutActionType = 1
	PlayerTimeoutActionType_PLAYER_TIMEOUT_ACTION_TRIBUTE_SELECT PlayerTimeoutActionType = 2
	PlayerTimeoutActionType_PLAYER_TIMEOUT_ACTION_RETURN_TRIBUTE PlayerTimeoutActionType = 3
)

// Enum value maps for PlayerTimeoutActionType.
var (
	PlayerTimeoutActionType_name = map[int32]string{
		0: "PLAYER_TIMEOUT_ACTION_UNSPECIFIED",
		1: "PLAYER_TIMEOUT_ACTION_PLAY_DECISION",
		2: "PLAYER_TIMEOUT_ACTION_TRIBUTE_SELECT",
		3: "PLAYER_TIMEOUT_ACTION_RETURN_TRIBUTE",
	}
	PlayerTimeoutActionType_value = map[string]int32{
		"PLAYER_TIMEOUT_ACTION_UNSPECIFIED":    0,
		"PLAYER_TIMEOUT_ACTION_PLAY_DECISION":  1,
		"PLAYER_TIMEOUT_ACTION_TRIBUTE_SELECT": 2,
		"PLAYER_TIMEOUT_ACTION_RETURN_TRIBUTE": 3,
	}
)

func (x PlayerTimeoutActionType) Enum() *PlayerTimeoutActionType {
	p := new(PlayerTimeoutActionType)
	*p = x
	return p
}

func (x PlayerTimeoutActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerTimeoutActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[3].Descriptor()
}

func (PlayerTimeoutActionType) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[3]
}

func (x PlayerTimeoutActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerTimeoutActionType.Descriptor instead.
func (PlayerTimeoutActionType) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{3}
}

// Card 表示一张扑克牌
// 简化版本，只包含用于前端渲染和逻辑判断的核心字段
type Card struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 花色编号：0=黑桃(Spade), 1=红桃(Heart), 2=梅花(Club), 3=方块(Diamond), -1=Joker
	Suit int32 `protobuf:"varint,1,opt,name=suit,proto3" json:"suit,omitempty"`
	// 牌的数字值，范围 1-16
	// 2-10=数字牌, 11=J, 12=Q, 13=K, 14=A, 15=小王(黑王), 16=大王(红王)
	// 注意：级牌不是固定的 rank 值，而是根据 deal_level 动态判断
	//
	//	当 rank == deal_level 时，该牌为级牌；其中红桃花色的级牌为逢人配(wildcard)
	Rank int32 `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	// 牌在整副牌中的唯一索引，范围 0-107
	// 用于精确定位某张具体的牌（避免相同花色和数字的牌混淆）
	DeckIndex     int32 `protobuf:"varint,3,opt,name=deck_index,json=deckIndex,proto3" json:"deck_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *Card) GetSuit() int32 {
	if x != nil {
		return x.Suit
	}
	return 0
}

func (x *Card) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *Card) GetDeckIndex() int32 {
	if x != nil {
		return x.DeckIndex
	}
	return 0
}

// PlayerBasicInfo 玩家基本信息（公开信息）
type PlayerBasicInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 玩家唯一标识符
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 玩家用户名
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// 玩家座位号，范围 0-3
	Seat int32 `protobuf:"varint,3,opt,name=seat,proto3" json:"seat,omitempty"`
	// 所属队伍编号，0 或 1
	TeamNum       int32 `protobuf:"varint,4,opt,name=team_num,json=teamNum,proto3" json:"team_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerBasicInfo) Reset() {
	*x = PlayerBasicInfo{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerBasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBasicInfo) ProtoMessage() {}

func (x *PlayerBasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBasicInfo.ProtoReflect.Descriptor instead.
func (*PlayerBasicInfo) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerBasicInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayerBasicInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerBasicInfo) GetSeat() int32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *PlayerBasicInfo) GetTeamNum() int32 {
	if x != nil {
		return x.TeamNum
	}
	return 0
}

// MatchStartedPayload 比赛开始事件数据
type MatchStartedPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 4名玩家信息（按座位号0-3顺序）
	Players []*PlayerBasicInfo `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	// 初始等级 [team0_level, team1_level]，通常为 [2, 2]
	InitialLevels []int32 `protobuf:"varint,2,rep,packed,name=initial_levels,json=initialLevels,proto3" json:"initial_levels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchStartedPayload) Reset() {
	*x = MatchStartedPayload{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchStartedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStartedPayload) ProtoMessage() {}

func (x *MatchStartedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStartedPayload.ProtoReflect.Descriptor instead.
func (*MatchStartedPayload) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

func (x *MatchStartedPayload) GetPlayers() []*PlayerBasicInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *MatchStartedPayload) GetInitialLevels() []int32 {
	if x != nil {
		return x.InitialLevels
	}
	return nil
}

// MatchEndedPayload 比赛结束事件数据
type MatchEndedPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 获胜队伍编号，0 或 1
	Winner int32 `protobuf:"varint,1,opt,name=winner,proto3" json:"winner,omitempty"`
	// 最终等级 [team0_level, team1_level]
	FinalLevels []int32 `protobuf:"varint,2,rep,packed,name=final_levels,json=finalLevels,proto3" json:"final_levels,omitempty"`
	// 比赛总时长（毫秒）
	DurationMs int64 `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// 总局数
	TotalDeals    int32 `protobuf:"varint,4,opt,name=total_deals,json=totalDeals,proto3" json:"total_deals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchEndedPayload) Reset() {
	*x = MatchEndedPayload{}
	mi := &file_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchEndedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchEndedPayload) ProtoMessage() {}

func (x *MatchEndedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchEndedPayload.ProtoReflect.Descriptor instead.
func (*MatchEndedPayload) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{3}
}

func (x *MatchEndedPayload) GetWinner() int32 {
	if x != nil {
		return x.Winner
	}
	return 0
}

func (x *MatchEndedPayload) GetFinalLevels() []int32 {
	if x != nil {
		return x.FinalLevels
	}
	return nil
}

func (x *MatchEndedPayload) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *MatchEndedPayload) GetTotalDeals() int32 {
	if x != nil {
		return x.TotalDeals
	}
	return 0
}

// DealStartedPayload 牌局开始事件数据
type DealStartedPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 当前打的等级（逢人配的基准牌值）
	DealLevel int32 `protobuf:"varint,1,opt,name=deal_level,json=dealLevel,proto3" json:"deal_level,omitempty"`
	// 两队当前等级 [team0_level, team1_level]
	TeamLevels    []int32 `protobuf:"varint,2,rep,packed,name=team_levels,json=teamLevels,proto3" json:"team_levels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DealStartedPayload) Reset() {
	*x = DealStartedPayload{}
	mi := &file_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealStartedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealStartedPayload) ProtoMessage() {}

func (x *DealStartedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealStartedPayload.ProtoReflect.Descriptor instead.
func (*DealStartedPayload) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{4}
}

func (x *DealStartedPayload) GetDealLevel() int32 {
	if x != nil {
		return x.DealLevel
	}
	return 0
}

func (x *DealStartedPayload) GetTeamLevels() []int32 {
	if x != nil {
		return x.TeamLevels
	}
	return nil
}

// CardsDealtPayload 发牌完成事件数据
type CardsDealtPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 每人分得的牌数（通常为27张）
	CardCount     int32 `protobuf:"varint,1,opt,name=card_count,json=cardCount,proto3" json:"card_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardsDealtPayload) Reset() {
	*x = CardsDealtPayload{}
	mi := &file_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardsDealtPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardsDealtPayload) ProtoMessage() {}

func (x *CardsDealtPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardsDealtPayload.ProtoReflect.Descriptor instead.
func (*CardsDealtPayload) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{5}
}

func (x *CardsDealtPayload) GetCardCount() int32 {
	if x != nil {
		return x.CardCount
	}
	return 0
}

// DealEndedPayload 牌局结束事件数据
type DealEndedPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 当前打的等级（逢人配的基准牌值）
	DealLevel int32 `protobuf:"varint,1,opt,name=deal_level,json=dealLevel,proto3" json:"deal_level,omitempty"`
	// 玩家排名（座位号）[第1名, 第2名, 第3名, 第4名]
	Rankings []int32 `protobuf:"varint,2,rep,packed,name=rankings,proto3" json:"rankings,omitempty"`
	// 胜利类型
	VictoryType VictoryType `protobuf:"varint,3,opt,name=victory_type,json=victoryType,proto3,enum=guandan.event.VictoryType" json:"victory_type,omitempty"`
	// 获胜队伍编号，0 或 1
	WinningTeam int32 `protobuf:"varint,4,opt,name=winning_team,json=winningTeam,proto3" json:"winning_team,omitempty"`
	// 等级变化 [team0_change, team1_change]
	// 正数表示升级，负数表示降级（通常不会降级）
	LevelChange []int32 `protobuf:"varint,5,rep,packed,name=level_change,json=levelChange,proto3" json:"level_change,omitempty"`
	// 本局耗时（毫秒）
	DurationMs int64 `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// 总轮次数
	TrickCount    int32 `protobuf:"varint,7,opt,name=trick_count,json=trickCount,proto3" json:"trick_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DealEndedPayload) Reset() {
	*x = DealEndedPayload{}
	mi := &file_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealEndedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealEndedPayload) ProtoMessage() {}

func (x *DealEndedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealEndedPayload.ProtoReflect.Descriptor instead.
func (*DealEndedPayload) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{6}
}

func (x *DealEndedPayload) GetDealLevel() int32 {
	if x != nil {
		return x.DealLevel
	}
	return 0
}

func (x *DealEndedPayload) GetRankings() []int32 {
	if x != nil {
		return x.Rankings
	}
	return nil
}

func (x *DealEndedPayload) GetVictoryType() VictoryType {
	if x != nil {
		return x.VictoryType
	}
	return VictoryType_VICTORY_TYPE_UNSPECIFIED
}

func (x *DealEndedPayload) GetWinningTeam() int32 {
	if x != nil {
		return x.WinningTeam
	}
	return 0
}

func (x *DealEndedPayload) GetLevelChange() []int32 {
	if x != nil {
		return x.LevelChange
	}
	return nil
}

func (x *DealEndedPayload) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *DealEndedPayload) GetTrickCount() int32 {
	if x != nil {
		return x.TrickCount
	}
	return 0
}

// TributeStartedPayload 进贡阶段开始事件数据
type TributeStartedPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 进贡类型："double_down"(双下), "single_last"(单下), "partner_last"(末游), "none"(无需进贡)
	TributeType TributeType `protobuf:"varint,1,opt,name=tribute_type,json=tributeType,proto3,enum=guandan.event.TributeType" json:"tribute_type,omitempty"`
	// 进贡方座位列表（败方玩家座位号）
	Givers []int32 `protobuf:"varint,2,rep,packed,name=givers,proto3" json:"givers,omitempty"`
	// 收贡方座位列表（胜方玩家座位号）
	Receivers     []int32 `protobuf:"varint,3,rep,packed,name=receivers,proto3" json:"receivers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TributeStartedPayload) Reset() {
	*x = TributeStartedPayload{}
	mi := &file_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TributeStartedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TributeStartedPayload) ProtoMessage() {}

func (x *TributeStartedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TributeStartedPayload.ProtoReflect.Descriptor instead.
func (*TributeStartedPayload) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{7}
}

func (x *TributeStartedPayload) GetTributeType() TributeType {
	if x != nil {
		return x.TributeType
	}
	return TributeType_TRIBUTE_TYPE_UNSPECIFIED
}

func (x *TributeStartedPayload) GetGivers() []int32 {
	if x != nil {
		return x.Givers
	}
	return nil
}

func (x *TributeStartedPayload) GetReceivers() []int32 {
	if x != nil {
		return x.Receivers
	}
	return nil
}

// TributeExemptedPayload 免贡事件数据
// 当败方玩家持有2张及以上大王时，可以免除进贡
type TributeExemptedPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 持有大王的玩家映射 seat -> big_joker_count
	// 仅包含败方玩家的信息
	BigJokerHolders map[int32]int32 `protobuf:"bytes,1,rep,name=big_joker_holders,json=bigJokerHolders,proto3" json:"big_joker_holders,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TributeExemptedPayload) Reset() {
	*x = TributeExemptedPayload{}
	mi := &file_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TributeExemptedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TributeExemptedPayload) ProtoMessage() {}

func (x *TributeExemptedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TributeExemptedPayload.ProtoReflect.Descriptor instead.
func (*TributeExemptedPayload) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{8}
}

func (x *TributeExemptedPayload) GetBigJokerHolders() map[int32]int32 {
	if x != nil {
		return x.BigJokerHolders
	}
	return nil
}

// TributeCardSubmittedPayload 贡牌提交事件数据
type TributeCardSubmittedPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 贡出的牌
	SubmittedCard *Card `protobuf:"bytes,1,opt,name=submitted_card,json=submittedCard,proto3" json:"submitted_card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TributeCardSubmittedPayload) Reset() {
	*x = TributeCardSubmittedPayload{}
	mi := &file_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TributeCardSubmittedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TributeCardSubmittedPayload) ProtoMessage() {}

func (x *TributeCardSubmittedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TributeCardSubmittedPayload.ProtoReflect.Descriptor instead.
func (*TributeCardSubmittedPayload) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{9}
}

func (x *TributeCardSubmittedPayload) GetSubmittedCard() *Card {
	if x != nil {
		return x.SubmittedCard
	}
	return nil
}

// TributeCardSelectedPayload 选牌事件数据（双下场景）
// 玩家从贡牌池中选择牌
type TributeCardSelectedPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 被选中的牌
	SelectedCard *Card `protobuf:"bytes,1,opt,name=selected_card,json=selectedCard,proto3" json:"selected_card,omitempty"`
	// 是否自动选择（超时，或仅有贡牌池仅1张牌时，会自动选择）
	IsAuto        bool `protobuf:"varint,2,opt,name=is_auto,json=isAuto,proto3" json:"is_auto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TributeCardSelectedPayload) Reset() {
	*x = TributeCardSelectedPayload{}
	mi := &file_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TributeCardSelectedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TributeCardSelectedPayload) ProtoMessage() {}

func (x *TributeCardSelectedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TributeCardSelectedPayload.ProtoReflect.Descriptor instead.
func (*TributeCardSelectedPayload) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{10}
}

func (x *TributeCardSelectedPayload) GetSelectedCard() *Card {
	if x != nil {
		return x.SelectedCard
	}
	return nil
}

func (x *TributeCardSelectedPayload) GetIsAuto() bool {
	if x != nil {
		return x.IsAuto
	}
	return false
}

// TributeCardReturnedPayload 还贡事件数据
type TributeCardReturnedPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 还贡的牌
	ReturnedCard *Card `protobuf:"bytes,1,opt,name=returned_card,json=returnedCard,proto3" json:"returned_card,omitempty"`
	// 还贡目标玩家座位号
	TargetPlayer int32 `protobuf:"varint,2,opt,name=target_player,json=targetPlayer,proto3" json:"target_player,omitempty"`
	// 是否自动选择（超时会自动选择）
	IsAuto        bool `protobuf:"varint,3,opt,name=is_auto,json=isAuto,proto3" json:"is_auto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TributeCardReturnedPayload) Reset() {
	*x = TributeCardReturnedPayload{}
	mi := &file_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TributeCardReturnedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TributeCardReturnedPayload) ProtoMessage() {}

func (x *TributeCardReturnedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TributeCardReturnedPayload.ProtoReflect.Descriptor instead.
func (*TributeCardReturnedPayload) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{11}
}

func (x *TributeCardReturnedPayload) GetReturnedCard() *Card {
	if x != nil {
		return x.ReturnedCard
	}
	return nil
}

func (x *TributeCardReturnedPayload) GetTargetPlayer() int32 {
	if x != nil {
		return x.TargetPlayer
	}
	return 0
}

func (x *TributeCardReturnedPayload) GetIsAuto() bool {
	if x != nil {
		return x.IsAuto
	}
	return false
}

// TributeCompletedPayload 进贡阶段结束事件数据
// 空 payload，仅用于标识进贡阶段已完成
type TributeCompletedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TributeCompletedPayload) Reset() {
	*x = TributeCompletedPayload{}
	mi := &file_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TributeCompletedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TributeCompletedPayload) ProtoMessage() {}

func (x *TributeCompletedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TributeCompletedPayload.ProtoReflect.Descriptor instead.
func (*TributeCompletedPayload) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{12}
}

// TrickStartedPayload 轮次开始事件数据
type TrickStartedPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 本轮领先出牌的玩家座位号
	Leader int32 `protobuf:"varint,1,opt,name=leader,proto3" json:"leader,omitempty"`
	// 是否为本局第一轮
	IsFirstTrick bool `protobuf:"varint,2,opt,name=is_first_trick,json=isFirstTrick,proto3" json:"is_first_trick,omitempty"`
	// 还有手牌的玩家座位号列表
	RemainingPlayers []int32 `protobuf:"varint,3,rep,packed,name=remaining_players,json=remainingPlayers,proto3" json:"remaining_players,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TrickStartedPayload) Reset() {
	*x = TrickStartedPayload{}
	mi := &file_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrickStartedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrickStartedPayload) ProtoMessage() {}

func (x *TrickStartedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrickStartedPayload.ProtoReflect.Descriptor instead.
func (*TrickStartedPayload) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{13}
}

func (x *TrickStartedPayload) GetLeader() int32 {
	if x != nil {
		return x.Leader
	}
	return 0
}

func (x *TrickStartedPayload) GetIsFirstTrick() bool {
	if x != nil {
		return x.IsFirstTrick
	}
	return false
}

func (x *TrickStartedPayload) GetRemainingPlayers() []int32 {
	if x != nil {
		return x.RemainingPlayers
	}
	return nil
}

// TrickEndedPayload 轮次结束事件数据
type TrickEndedPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 本轮获胜玩家座位号（下一轮领先出牌者）
	TrickWinner   int32 `protobuf:"varint,1,opt,name=trick_winner,json=trickWinner,proto3" json:"trick_winner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrickEndedPayload) Reset() {
	*x = TrickEndedPayload{}
	mi := &file_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrickEndedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrickEndedPayload) ProtoMessage() {}

func (x *TrickEndedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrickEndedPayload.ProtoReflect.Descriptor instead.
func (*TrickEndedPayload) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{14}
}

func (x *TrickEndedPayload) GetTrickWinner() int32 {
	if x != nil {
		return x.TrickWinner
	}
	return 0
}

// PlayerPlayedPayload 玩家出牌事件数据
type PlayerPlayedPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 玩家出的牌列表
	Cards         []*Card `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerPlayedPayload) Reset() {
	*x = PlayerPlayedPayload{}
	mi := &file_event_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerPlayedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerPlayedPayload) ProtoMessage() {}

func (x *PlayerPlayedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerPlayedPayload.ProtoReflect.Descriptor instead.
func (*PlayerPlayedPayload) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{15}
}

func (x *PlayerPlayedPayload) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

// PlayerPassedPayload 玩家过牌事件数据
// 空 payload，actor_seat 已在 GameEvent 顶层字段标识
type PlayerPassedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerPassedPayload) Reset() {
	*x = PlayerPassedPayload{}
	mi := &file_event_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerPassedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerPassedPayload) ProtoMessage() {}

func (x *PlayerPassedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerPassedPayload.ProtoReflect.Descriptor instead.
func (*PlayerPassedPayload) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{16}
}

type PlayerTimeoutPayload struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ActionType    PlayerTimeoutActionType `protobuf:"varint,1,opt,name=action_type,json=actionType,proto3,enum=guandan.event.PlayerTimeoutActionType" json:"action_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerTimeoutPayload) Reset() {
	*x = PlayerTimeoutPayload{}
	mi := &file_event_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerTimeoutPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerTimeoutPayload) ProtoMessage() {}

func (x *PlayerTimeoutPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerTimeoutPayload.ProtoReflect.Descriptor instead.
func (*PlayerTimeoutPayload) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{17}
}

func (x *PlayerTimeoutPayload) GetActionType() PlayerTimeoutActionType {
	if x != nil {
		return x.ActionType
	}
	return PlayerTimeoutActionType_PLAYER_TIMEOUT_ACTION_UNSPECIFIED
}

// PlayerDisconnectPayload 玩家断线事件数据
type PlayerDisconnectPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否启用自动托管
	AutoPlay      bool `protobuf:"varint,1,opt,name=auto_play,json=autoPlay,proto3" json:"auto_play,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerDisconnectPayload) Reset() {
	*x = PlayerDisconnectPayload{}
	mi := &file_event_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerDisconnectPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDisconnectPayload) ProtoMessage() {}

func (x *PlayerDisconnectPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDisconnectPayload.ProtoReflect.Descriptor instead.
func (*PlayerDisconnectPayload) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{18}
}

func (x *PlayerDisconnectPayload) GetAutoPlay() bool {
	if x != nil {
		return x.AutoPlay
	}
	return false
}

// PlayerReconnectPayload 玩家重连事件数据
type PlayerReconnectPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 重连后是否仍处于自动托管状态（通常为 false）
	AutoPlay      bool `protobuf:"varint,1,opt,name=auto_play,json=autoPlay,proto3" json:"auto_play,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerReconnectPayload) Reset() {
	*x = PlayerReconnectPayload{}
	mi := &file_event_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerReconnectPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerReconnectPayload) ProtoMessage() {}

func (x *PlayerReconnectPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerReconnectPayload.ProtoReflect.Descriptor instead.
func (*PlayerReconnectPayload) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{19}
}

func (x *PlayerReconnectPayload) GetAutoPlay() bool {
	if x != nil {
		return x.AutoPlay
	}
	return false
}

// GameEvent 游戏事件统一封装
// 所有游戏事件共用此顶层结构，通过 oneof payload 区分具体事件类型
type GameEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 比赛唯一标识符（必填）
	MatchId string `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	// 局索引（从 0 开始）
	// 仅在局级及以下事件中填写
	DealIndex *int32 `protobuf:"varint,2,opt,name=deal_index,json=dealIndex,proto3,oneof" json:"deal_index,omitempty"`
	// 轮次索引（从 0 开始）
	// 仅在轮级及玩家行为事件中填写
	TrickIndex *int32 `protobuf:"varint,3,opt,name=trick_index,json=trickIndex,proto3,oneof" json:"trick_index,omitempty"`
	// 行为玩家座位号（0-3）
	// 仅在玩家行为事件中填写
	ActorSeat *int32 `protobuf:"varint,4,opt,name=actor_seat,json=actorSeat,proto3,oneof" json:"actor_seat,omitempty"`
	// 事件序列号（全局递增）
	// 用于事件排序和去重
	Seq int64 `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`
	// 事件创建时间戳（毫秒）
	CreatedAtMs int64 `protobuf:"varint,6,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	// 事件类型（便于快速识别和过滤事件）
	Type EventType `protobuf:"varint,7,opt,name=type,proto3,enum=guandan.event.EventType" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GameEvent_MatchStarted
	//	*GameEvent_MatchEnded
	//	*GameEvent_DealStarted
	//	*GameEvent_CardsDealt
	//	*GameEvent_DealEnded
	//	*GameEvent_TributeStarted
	//	*GameEvent_TributeExempted
	//	*GameEvent_TributeCardSubmitted
	//	*GameEvent_TributeCardSelected
	//	*GameEvent_TributeCardReturned
	//	*GameEvent_TributeCompleted
	//	*GameEvent_TrickStarted
	//	*GameEvent_TrickEnded
	//	*GameEvent_PlayerPlayed
	//	*GameEvent_PlayerPassed
	//	*GameEvent_PlayerTimeout
	//	*GameEvent_PlayerDisconnect
	//	*GameEvent_PlayerReconnect
	Payload       isGameEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEvent) Reset() {
	*x = GameEvent{}
	mi := &file_event_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent) ProtoMessage() {}

func (x *GameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent.ProtoReflect.Descriptor instead.
func (*GameEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{20}
}

func (x *GameEvent) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *GameEvent) GetDealIndex() int32 {
	if x != nil && x.DealIndex != nil {
		return *x.DealIndex
	}
	return 0
}

func (x *GameEvent) GetTrickIndex() int32 {
	if x != nil && x.TrickIndex != nil {
		return *x.TrickIndex
	}
	return 0
}

func (x *GameEvent) GetActorSeat() int32 {
	if x != nil && x.ActorSeat != nil {
		return *x.ActorSeat
	}
	return 0
}

func (x *GameEvent) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GameEvent) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

func (x *GameEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *GameEvent) GetPayload() isGameEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GameEvent) GetMatchStarted() *MatchStartedPayload {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_MatchStarted); ok {
			return x.MatchStarted
		}
	}
	return nil
}

func (x *GameEvent) GetMatchEnded() *MatchEndedPayload {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_MatchEnded); ok {
			return x.MatchEnded
		}
	}
	return nil
}

func (x *GameEvent) GetDealStarted() *DealStartedPayload {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_DealStarted); ok {
			return x.DealStarted
		}
	}
	return nil
}

func (x *GameEvent) GetCardsDealt() *CardsDealtPayload {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_CardsDealt); ok {
			return x.CardsDealt
		}
	}
	return nil
}

func (x *GameEvent) GetDealEnded() *DealEndedPayload {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_DealEnded); ok {
			return x.DealEnded
		}
	}
	return nil
}

func (x *GameEvent) GetTributeStarted() *TributeStartedPayload {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_TributeStarted); ok {
			return x.TributeStarted
		}
	}
	return nil
}

func (x *GameEvent) GetTributeExempted() *TributeExemptedPayload {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_TributeExempted); ok {
			return x.TributeExempted
		}
	}
	return nil
}

func (x *GameEvent) GetTributeCardSubmitted() *TributeCardSubmittedPayload {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_TributeCardSubmitted); ok {
			return x.TributeCardSubmitted
		}
	}
	return nil
}

func (x *GameEvent) GetTributeCardSelected() *TributeCardSelectedPayload {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_TributeCardSelected); ok {
			return x.TributeCardSelected
		}
	}
	return nil
}

func (x *GameEvent) GetTributeCardReturned() *TributeCardReturnedPayload {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_TributeCardReturned); ok {
			return x.TributeCardReturned
		}
	}
	return nil
}

func (x *GameEvent) GetTributeCompleted() *TributeCompletedPayload {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_TributeCompleted); ok {
			return x.TributeCompleted
		}
	}
	return nil
}

func (x *GameEvent) GetTrickStarted() *TrickStartedPayload {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_TrickStarted); ok {
			return x.TrickStarted
		}
	}
	return nil
}

func (x *GameEvent) GetTrickEnded() *TrickEndedPayload {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_TrickEnded); ok {
			return x.TrickEnded
		}
	}
	return nil
}

func (x *GameEvent) GetPlayerPlayed() *PlayerPlayedPayload {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_PlayerPlayed); ok {
			return x.PlayerPlayed
		}
	}
	return nil
}

func (x *GameEvent) GetPlayerPassed() *PlayerPassedPayload {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_PlayerPassed); ok {
			return x.PlayerPassed
		}
	}
	return nil
}

func (x *GameEvent) GetPlayerTimeout() *PlayerTimeoutPayload {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_PlayerTimeout); ok {
			return x.PlayerTimeout
		}
	}
	return nil
}

func (x *GameEvent) GetPlayerDisconnect() *PlayerDisconnectPayload {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_PlayerDisconnect); ok {
			return x.PlayerDisconnect
		}
	}
	return nil
}

func (x *GameEvent) GetPlayerReconnect() *PlayerReconnectPayload {
	if x != nil {
		if x, ok := x.Payload.(*GameEvent_PlayerReconnect); ok {
			return x.PlayerReconnect
		}
	}
	return nil
}

type isGameEvent_Payload interface {
	isGameEvent_Payload()
}

type GameEvent_MatchStarted struct {
	// 比赛级事件（field number 10-19）
	MatchStarted *MatchStartedPayload `protobuf:"bytes,10,opt,name=match_started,json=matchStarted,proto3,oneof"`
}

type GameEvent_MatchEnded struct {
	MatchEnded *MatchEndedPayload `protobuf:"bytes,11,opt,name=match_ended,json=matchEnded,proto3,oneof"`
}

type GameEvent_DealStarted struct {
	// 局级事件（field number 20-29）
	DealStarted *DealStartedPayload `protobuf:"bytes,20,opt,name=deal_started,json=dealStarted,proto3,oneof"`
}

type GameEvent_CardsDealt struct {
	CardsDealt *CardsDealtPayload `protobuf:"bytes,21,opt,name=cards_dealt,json=cardsDealt,proto3,oneof"`
}

type GameEvent_DealEnded struct {
	DealEnded *DealEndedPayload `protobuf:"bytes,22,opt,name=deal_ended,json=dealEnded,proto3,oneof"`
}

type GameEvent_TributeStarted struct {
	// 进贡阶段事件（field number 30-39）
	TributeStarted *TributeStartedPayload `protobuf:"bytes,30,opt,name=tribute_started,json=tributeStarted,proto3,oneof"`
}

type GameEvent_TributeExempted struct {
	TributeExempted *TributeExemptedPayload `protobuf:"bytes,31,opt,name=tribute_exempted,json=tributeExempted,proto3,oneof"`
}

type GameEvent_TributeCardSubmitted struct {
	TributeCardSubmitted *TributeCardSubmittedPayload `protobuf:"bytes,32,opt,name=tribute_card_submitted,json=tributeCardSubmitted,proto3,oneof"`
}

type GameEvent_TributeCardSelected struct {
	TributeCardSelected *TributeCardSelectedPayload `protobuf:"bytes,33,opt,name=tribute_card_selected,json=tributeCardSelected,proto3,oneof"`
}

type GameEvent_TributeCardReturned struct {
	TributeCardReturned *TributeCardReturnedPayload `protobuf:"bytes,34,opt,name=tribute_card_returned,json=tributeCardReturned,proto3,oneof"`
}

type GameEvent_TributeCompleted struct {
	TributeCompleted *TributeCompletedPayload `protobuf:"bytes,35,opt,name=tribute_completed,json=tributeCompleted,proto3,oneof"`
}

type GameEvent_TrickStarted struct {
	// 轮次级事件（field number 40-49）
	TrickStarted *TrickStartedPayload `protobuf:"bytes,40,opt,name=trick_started,json=trickStarted,proto3,oneof"`
}

type GameEvent_TrickEnded struct {
	TrickEnded *TrickEndedPayload `protobuf:"bytes,41,opt,name=trick_ended,json=trickEnded,proto3,oneof"`
}

type GameEvent_PlayerPlayed struct {
	// 玩家行为事件（field number 50-59）
	PlayerPlayed *PlayerPlayedPayload `protobuf:"bytes,50,opt,name=player_played,json=playerPlayed,proto3,oneof"`
}

type GameEvent_PlayerPassed struct {
	PlayerPassed *PlayerPassedPayload `protobuf:"bytes,51,opt,name=player_passed,json=playerPassed,proto3,oneof"`
}

type GameEvent_PlayerTimeout struct {
	PlayerTimeout *PlayerTimeoutPayload `protobuf:"bytes,52,opt,name=player_timeout,json=playerTimeout,proto3,oneof"`
}

type GameEvent_PlayerDisconnect struct {
	PlayerDisconnect *PlayerDisconnectPayload `protobuf:"bytes,53,opt,name=player_disconnect,json=playerDisconnect,proto3,oneof"`
}

type GameEvent_PlayerReconnect struct {
	PlayerReconnect *PlayerReconnectPayload `protobuf:"bytes,54,opt,name=player_reconnect,json=playerReconnect,proto3,oneof"`
}

func (*GameEvent_MatchStarted) isGameEvent_Payload() {}

func (*GameEvent_MatchEnded) isGameEvent_Payload() {}

func (*GameEvent_DealStarted) isGameEvent_Payload() {}

func (*GameEvent_CardsDealt) isGameEvent_Payload() {}

func (*GameEvent_DealEnded) isGameEvent_Payload() {}

func (*GameEvent_TributeStarted) isGameEvent_Payload() {}

func (*GameEvent_TributeExempted) isGameEvent_Payload() {}

func (*GameEvent_TributeCardSubmitted) isGameEvent_Payload() {}

func (*GameEvent_TributeCardSelected) isGameEvent_Payload() {}

func (*GameEvent_TributeCardReturned) isGameEvent_Payload() {}

func (*GameEvent_TributeCompleted) isGameEvent_Payload() {}

func (*GameEvent_TrickStarted) isGameEvent_Payload() {}

func (*GameEvent_TrickEnded) isGameEvent_Payload() {}

func (*GameEvent_PlayerPlayed) isGameEvent_Payload() {}

func (*GameEvent_PlayerPassed) isGameEvent_Payload() {}

func (*GameEvent_PlayerTimeout) isGameEvent_Payload() {}

func (*GameEvent_PlayerDisconnect) isGameEvent_Payload() {}

func (*GameEvent_PlayerReconnect) isGameEvent_Payload() {}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\rguandan.event\"M\n" +
	"\x04Card\x12\x12\n" +
	"\x04suit\x18\x01 \x01(\x05R\x04suit\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x05R\x04rank\x12\x1d\n" +
	"\n" +
	"deck_index\x18\x03 \x01(\x05R\tdeckIndex\"l\n" +
	"\x0fPlayerBasicInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04seat\x18\x03 \x01(\x05R\x04seat\x12\x19\n" +
	"\bteam_num\x18\x04 \x01(\x05R\ateamNum\"v\n" +
	"\x13MatchStartedPayload\x128\n" +
	"\aplayers\x18\x01 \x03(\v2\x1e.guandan.event.PlayerBasicInfoR\aplayers\x12%\n" +
	"\x0einitial_levels\x18\x02 \x03(\x05R\rinitialLevels\"\x90\x01\n" +
	"\x11MatchEndedPayload\x12\x16\n" +
	"\x06winner\x18\x01 \x01(\x05R\x06winner\x12!\n" +
	"\ffinal_levels\x18\x02 \x03(\x05R\vfinalLevels\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\x12\x1f\n" +
	"\vtotal_deals\x18\x04 \x01(\x05R\n" +
	"totalDeals\"T\n" +
	"\x12DealStartedPayload\x12\x1d\n" +
	"\n" +
	"deal_level\x18\x01 \x01(\x05R\tdealLevel\x12\x1f\n" +
	"\vteam_levels\x18\x02 \x03(\x05R\n" +
	"teamLevels\"2\n" +
	"\x11CardsDealtPayload\x12\x1d\n" +
	"\n" +
	"card_count\x18\x01 \x01(\x05R\tcardCount\"\x94\x02\n" +
	"\x10DealEndedPayload\x12\x1d\n" +
	"\n" +
	"deal_level\x18\x01 \x01(\x05R\tdealLevel\x12\x1a\n" +
	"\brankings\x18\x02 \x03(\x05R\brankings\x12=\n" +
	"\fvictory_type\x18\x03 \x01(\x0e2\x1a.guandan.event.VictoryTypeR\vvictoryType\x12!\n" +
	"\fwinning_team\x18\x04 \x01(\x05R\vwinningTeam\x12!\n" +
	"\flevel_change\x18\x05 \x03(\x05R\vlevelChange\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\x12\x1f\n" +
	"\vtrick_count\x18\a \x01(\x05R\n" +
	"trickCount\"\x8c\x01\n" +
	"\x15TributeStartedPayload\x12=\n" +
	"\ftribute_type\x18\x01 \x01(\x0e2\x1a.guandan.event.TributeTypeR\vtributeType\x12\x16\n" +
	"\x06givers\x18\x02 \x03(\x05R\x06givers\x12\x1c\n" +
	"\treceivers\x18\x03 \x03(\x05R\treceivers\"\xc4\x01\n" +
	"\x16TributeExemptedPayload\x12f\n" +
	"\x11big_joker_holders\x18\x01 \x03(\v2:.guandan.event.TributeExemptedPayload.BigJokerHoldersEntryR\x0fbigJokerHolders\x1aB\n" +
	"\x14BigJokerHoldersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"Y\n" +
	"\x1bTributeCardSubmittedPayload\x12:\n" +
	"\x0esubmitted_card\x18\x01 \x01(\v2\x13.guandan.event.CardR\rsubmittedCard\"o\n" +
	"\x1aTributeCardSelectedPayload\x128\n" +
	"\rselected_card\x18\x01 \x01(\v2\x13.guandan.event.CardR\fselectedCard\x12\x17\n" +
	"\ais_auto\x18\x02 \x01(\bR\x06isAuto\"\x94\x01\n" +
	"\x1aTributeCardReturnedPayload\x128\n" +
	"\rreturned_card\x18\x01 \x01(\v2\x13.guandan.event.CardR\freturnedCard\x12#\n" +
	"\rtarget_player\x18\x02 \x01(\x05R\ftargetPlayer\x12\x17\n" +
	"\ais_auto\x18\x03 \x01(\bR\x06isAuto\"\x19\n" +
	"\x17TributeCompletedPayload\"\x80\x01\n" +
	"\x13TrickStartedPayload\x12\x16\n" +
	"\x06leader\x18\x01 \x01(\x05R\x06leader\x12$\n" +
	"\x0eis_first_trick\x18\x02 \x01(\bR\fisFirstTrick\x12+\n" +
	"\x11remaining_players\x18\x03 \x03(\x05R\x10remainingPlayers\"6\n" +
	"\x11TrickEndedPayload\x12!\n" +
	"\ftrick_winner\x18\x01 \x01(\x05R\vtrickWinner\"@\n" +
	"\x13PlayerPlayedPayload\x12)\n" +
	"\x05cards\x18\x01 \x03(\v2\x13.guandan.event.CardR\x05cards\"\x15\n" +
	"\x13PlayerPassedPayload\"_\n" +
	"\x14PlayerTimeoutPayload\x12G\n" +
	"\vaction_type\x18\x01 \x01(\x0e2&.guandan.event.PlayerTimeoutActionTypeR\n" +
	"actionType\"6\n" +
	"\x17PlayerDisconnectPayload\x12\x1b\n" +
	"\tauto_play\x18\x01 \x01(\bR\bautoPlay\"5\n" +
	"\x16PlayerReconnectPayload\x12\x1b\n" +
	"\tauto_play\x18\x01 \x01(\bR\bautoPlay\"\xd1\r\n" +
	"\tGameEvent\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\"\n" +
	"\n" +
	"deal_index\x18\x02 \x01(\x05H\x01R\tdealIndex\x88\x01\x01\x12$\n" +
	"\vtrick_index\x18\x03 \x01(\x05H\x02R\n" +
	"trickIndex\x88\x01\x01\x12\"\n" +
	"\n" +
	"actor_seat\x18\x04 \x01(\x05H\x03R\tactorSeat\x88\x01\x01\x12\x10\n" +
	"\x03seq\x18\x05 \x01(\x03R\x03seq\x12\"\n" +
	"\rcreated_at_ms\x18\x06 \x01(\x03R\vcreatedAtMs\x12,\n" +
	"\x04type\x18\a \x01(\x0e2\x18.guandan.event.EventTypeR\x04type\x12I\n" +
	"\rmatch_started\x18\n" +
	" \x01(\v2\".guandan.event.MatchStartedPayloadH\x00R\fmatchStarted\x12C\n" +
	"\vmatch_ended\x18\v \x01(\v2 .guandan.event.MatchEndedPayloadH\x00R\n" +
	"matchEnded\x12F\n" +
	"\fdeal_started\x18\x14 \x01(\v2!.guandan.event.DealStartedPayloadH\x00R\vdealStarted\x12C\n" +
	"\vcards_dealt\x18\x15 \x01(\v2 .guandan.event.CardsDealtPayloadH\x00R\n" +
	"cardsDealt\x12@\n" +
	"\n" +
	"deal_ended\x18\x16 \x01(\v2\x1f.guandan.event.DealEndedPayloadH\x00R\tdealEnded\x12O\n" +
	"\x0ftribute_started\x18\x1e \x01(\v2$.guandan.event.TributeStartedPayloadH\x00R\x0etributeStarted\x12R\n" +
	"\x10tribute_exempted\x18\x1f \x01(\v2%.guandan.event.TributeExemptedPayloadH\x00R\x0ftributeExempted\x12b\n" +
	"\x16tribute_card_submitted\x18  \x01(\v2*.guandan.event.TributeCardSubmittedPayloadH\x00R\x14tributeCardSubmitted\x12_\n" +
	"\x15tribute_card_selected\x18! \x01(\v2).guandan.event.TributeCardSelectedPayloadH\x00R\x13tributeCardSelected\x12_\n" +
	"\x15tribute_card_returned\x18\" \x01(\v2).guandan.event.TributeCardReturnedPayloadH\x00R\x13tributeCardReturned\x12U\n" +
	"\x11tribute_completed\x18# \x01(\v2&.guandan.event.TributeCompletedPayloadH\x00R\x10tributeCompleted\x12I\n" +
	"\rtrick_started\x18( \x01(\v2\".guandan.event.TrickStartedPayloadH\x00R\ftrickStarted\x12C\n" +
	"\vtrick_ended\x18) \x01(\v2 .guandan.event.TrickEndedPayloadH\x00R\n" +
	"trickEnded\x12I\n" +
	"\rplayer_played\x182 \x01(\v2\".guandan.event.PlayerPlayedPayloadH\x00R\fplayerPlayed\x12I\n" +
	"\rplayer_passed\x183 \x01(\v2\".guandan.event.PlayerPassedPayloadH\x00R\fplayerPassed\x12L\n" +
	"\x0eplayer_timeout\x184 \x01(\v2#.guandan.event.PlayerTimeoutPayloadH\x00R\rplayerTimeout\x12U\n" +
	"\x11player_disconnect\x185 \x01(\v2&.guandan.event.PlayerDisconnectPayloadH\x00R\x10playerDisconnect\x12R\n" +
	"\x10player_reconnect\x186 \x01(\v2%.guandan.event.PlayerReconnectPayloadH\x00R\x0fplayerReconnectB\t\n" +
	"\apayloadB\r\n" +
	"\v_deal_indexB\x0e\n" +
	"\f_trick_indexB\r\n" +
	"\v_actor_seat*\x86\x01\n" +
	"\vVictoryType\x12\x1c\n" +
	"\x18VICTORY_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18VICTORY_TYPE_DOUBLE_DOWN\x10\x01\x12\x1c\n" +
	"\x18VICTORY_TYPE_SINGLE_LAST\x10\x02\x12\x1d\n" +
	"\x19VICTORY_TYPE_PARTNER_LAST\x10\x03*\xe3\x04\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18EVENT_TYPE_MATCH_STARTED\x10\x01\x12\x1a\n" +
	"\x16EVENT_TYPE_MATCH_ENDED\x10\x02\x12\x1b\n" +
	"\x17EVENT_TYPE_DEAL_STARTED\x10\n" +
	"\x12\x1a\n" +
	"\x16EVENT_TYPE_CARDS_DEALT\x10\v\x12\x19\n" +
	"\x15EVENT_TYPE_DEAL_ENDED\x10\f\x12\x1e\n" +
	"\x1aEVENT_TYPE_TRIBUTE_STARTED\x10\x14\x12\x1f\n" +
	"\x1bEVENT_TYPE_TRIBUTE_EXEMPTED\x10\x15\x12%\n" +
	"!EVENT_TYPE_TRIBUTE_CARD_SUBMITTED\x10\x16\x12$\n" +
	" EVENT_TYPE_TRIBUTE_CARD_SELECTED\x10\x17\x12$\n" +
	" EVENT_TYPE_TRIBUTE_CARD_RETURNED\x10\x18\x12 \n" +
	"\x1cEVENT_TYPE_TRIBUTE_COMPLETED\x10\x19\x12\x1c\n" +
	"\x18EVENT_TYPE_TRICK_STARTED\x10\x1e\x12\x1a\n" +
	"\x16EVENT_TYPE_TRICK_ENDED\x10\x1f\x12\x1c\n" +
	"\x18EVENT_TYPE_PLAYER_PLAYED\x10(\x12\x1c\n" +
	"\x18EVENT_TYPE_PLAYER_PASSED\x10)\x12\x1d\n" +
	"\x19EVENT_TYPE_PLAYER_TIMEOUT\x10*\x12 \n" +
	"\x1cEVENT_TYPE_PLAYER_DISCONNECT\x10+\x12\x1f\n" +
	"\x1bEVENT_TYPE_PLAYER_RECONNECT\x10,*\x9d\x01\n" +
	"\vTributeType\x12\x1c\n" +
	"\x18TRIBUTE_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TRIBUTE_TYPE_DOUBLE_DOWN\x10\x01\x12\x1c\n" +
	"\x18TRIBUTE_TYPE_SINGLE_LAST\x10\x02\x12\x1d\n" +
	"\x19TRIBUTE_TYPE_PARTNER_LAST\x10\x03\x12\x15\n" +
	"\x11TRIBUTE_TYPE_NONE\x10\x04*\xbd\x01\n" +
	"\x17PlayerTimeoutActionType\x12%\n" +
	"!PLAYER_TIMEOUT_ACTION_UNSPECIFIED\x10\x00\x12'\n" +
	"#PLAYER_TIMEOUT_ACTION_PLAY_DECISION\x10\x01\x12(\n" +
	"$PLAYER_TIMEOUT_ACTION_TRIBUTE_SELECT\x10\x02\x12(\n" +
	"$PLAYER_TIMEOUT_ACTION_RETURN_TRIBUTE\x10\x03B\x1bZ\x19guandan-world/proto/eventb\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_event_proto_goTypes = []any{
	(VictoryType)(0),                    // 0: guandan.event.VictoryType
	(EventType)(0),                      // 1: guandan.event.EventType
	(TributeType)(0),                    // 2: guandan.event.TributeType
	(PlayerTimeoutActionType)(0),        // 3: guandan.event.PlayerTimeoutActionType
	(*Card)(nil),                        // 4: guandan.event.Card
	(*PlayerBasicInfo)(nil),             // 5: guandan.event.PlayerBasicInfo
	(*MatchStartedPayload)(nil),         // 6: guandan.event.MatchStartedPayload
	(*MatchEndedPayload)(nil),           // 7: guandan.event.MatchEndedPayload
	(*DealStartedPayload)(nil),          // 8: guandan.event.DealStartedPayload
	(*CardsDealtPayload)(nil),           // 9: guandan.event.CardsDealtPayload
	(*DealEndedPayload)(nil),            // 10: guandan.event.DealEndedPayload
	(*TributeStartedPayload)(nil),       // 11: guandan.event.TributeStartedPayload
	(*TributeExemptedPayload)(nil),      // 12: guandan.event.TributeExemptedPayload
	(*TributeCardSubmittedPayload)(nil), // 13: guandan.event.TributeCardSubmittedPayload
	(*TributeCardSelectedPayload)(nil),  // 14: guandan.event.TributeCardSelectedPayload
	(*TributeCardReturnedPayload)(nil),  // 15: guandan.event.TributeCardReturnedPayload
	(*TributeCompletedPayload)(nil),     // 16: guandan.event.TributeCompletedPayload
	(*TrickStartedPayload)(nil),         // 17: guandan.event.TrickStartedPayload
	(*TrickEndedPayload)(nil),           // 18: guandan.event.TrickEndedPayload
	(*PlayerPlayedPayload)(nil),         // 19: guandan.event.PlayerPlayedPayload
	(*PlayerPassedPayload)(nil),         // 20: guandan.event.PlayerPassedPayload
	(*PlayerTimeoutPayload)(nil),        // 21: guandan.event.PlayerTimeoutPayload
	(*PlayerDisconnectPayload)(nil),     // 22: guandan.event.PlayerDisconnectPayload
	(*PlayerReconnectPayload)(nil),      // 23: guandan.event.PlayerReconnectPayload
	(*GameEvent)(nil),                   // 24: guandan.event.GameEvent
	nil,                                 // 25: guandan.event.TributeExemptedPayload.BigJokerHoldersEntry
}
var file_event_proto_depIdxs = []int32{
	5,  // 0: guandan.event.MatchStartedPayload.players:type_name -> guandan.event.PlayerBasicInfo
	0,  // 1: guandan.event.DealEndedPayload.victory_type:type_name -> guandan.event.VictoryType
	2,  // 2: guandan.event.TributeStartedPayload.tribute_type:type_name -> guandan.event.TributeType
	25, // 3: guandan.event.TributeExemptedPayload.big_joker_holders:type_name -> guandan.event.TributeExemptedPayload.BigJokerHoldersEntry
	4,  // 4: guandan.event.TributeCardSubmittedPayload.submitted_card:type_name -> guandan.event.Card
	4,  // 5: guandan.event.TributeCardSelectedPayload.selected_card:type_name -> guandan.event.Card
	4,  // 6: guandan.event.TributeCardReturnedPayload.returned_card:type_name -> guandan.event.Card
	4,  // 7: guandan.event.PlayerPlayedPayload.cards:type_name -> guandan.event.Card
	3,  // 8: guandan.event.PlayerTimeoutPayload.action_type:type_name -> guandan.event.PlayerTimeoutActionType
	1,  // 9: guandan.event.GameEvent.type:type_name -> guandan.event.EventType
	6,  // 10: guandan.event.GameEvent.match_started:type_name -> guandan.event.MatchStartedPayload
	7,  // 11: guandan.event.GameEvent.match_ended:type_name -> guandan.event.MatchEndedPayload
	8,  // 12: guandan.event.GameEvent.deal_started:type_name -> guandan.event.DealStartedPayload
	9,  // 13: guandan.event.GameEvent.cards_dealt:type_name -> guandan.event.CardsDealtPayload
	10, // 14: guandan.event.GameEvent.deal_ended:type_name -> guandan.event.DealEndedPayload
	11, // 15: guandan.event.GameEvent.tribute_started:type_name -> guandan.event.TributeStartedPayload
	12, // 16: guandan.event.GameEvent.tribute_exempted:type_name -> guandan.event.TributeExemptedPayload
	13, // 17: guandan.event.GameEvent.tribute_card_submitted:type_name -> guandan.event.TributeCardSubmittedPayload
	14, // 18: guandan.event.GameEvent.tribute_card_selected:type_name -> guandan.event.TributeCardSelectedPayload
	15, // 19: guandan.event.GameEvent.tribute_card_returned:type_name -> guandan.event.TributeCardReturnedPayload
	16, // 20: guandan.event.GameEvent.tribute_completed:type_name -> guandan.event.TributeCompletedPayload
	17, // 21: guandan.event.GameEvent.trick_started:type_name -> guandan.event.TrickStartedPayload
	18, // 22: guandan.event.GameEvent.trick_ended:type_name -> guandan.event.TrickEndedPayload
	19, // 23: guandan.event.GameEvent.player_played:type_name -> guandan.event.PlayerPlayedPayload
	20, // 24: guandan.event.GameEvent.player_passed:type_name -> guandan.event.PlayerPassedPayload
	21, // 25: guandan.event.GameEvent.player_timeout:type_name -> guandan.event.PlayerTimeoutPayload
	22, // 26: guandan.event.GameEvent.player_disconnect:type_name -> guandan.event.PlayerDisconnectPayload
	23, // 27: guandan.event.GameEvent.player_reconnect:type_name -> guandan.event.PlayerReconnectPayload
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	file_event_proto_msgTypes[20].OneofWrappers = []any{
		(*GameEvent_MatchStarted)(nil),
		(*GameEvent_MatchEnded)(nil),
		(*GameEvent_DealStarted)(nil),
		(*GameEvent_CardsDealt)(nil),
		(*GameEvent_DealEnded)(nil),
		(*GameEvent_TributeStarted)(nil),
		(*GameEvent_TributeExempted)(nil),
		(*GameEvent_TributeCardSubmitted)(nil),
		(*GameEvent_TributeCardSelected)(nil),
		(*GameEvent_TributeCardReturned)(nil),
		(*GameEvent_TributeCompleted)(nil),
		(*GameEvent_TrickStarted)(nil),
		(*GameEvent_TrickEnded)(nil),
		(*GameEvent_PlayerPlayed)(nil),
		(*GameEvent_PlayerPassed)(nil),
		(*GameEvent_PlayerTimeout)(nil),
		(*GameEvent_PlayerDisconnect)(nil),
		(*GameEvent_PlayerReconnect)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		EnumInfos:         file_event_proto_enumTypes,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
