name: CI Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: guandan
          POSTGRES_PASSWORD: guandan
          POSTGRES_DB: guandan
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build backend
        run: |
          cd backend
          go mod download
          go build -v ./...

      - name: Run SDK tests
        run: |
          cd sdk
          go test ./... -v

      - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Run backend tests
        run: |
          cd backend
          go test ./... -v
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: guandan
          DB_USER: guandan
          DB_PASSWORD: guandan
          REDIS_HOST: localhost
          REDIS_PORT: 6379

  build-images:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: |
          cd backend
          docker build -t guandan-backend:latest .

      - name: Build frontend image
        run: |
          cd frontend
          docker build -t guandan-frontend:latest .

      - name: Test docker-compose
        run: |
          docker-compose -f docker-compose.yml build 