export const groundTruth: Record<string, string[] | null> = {
  "findMinPlay: should return null when no valid play exists": null,
  "findMinBomb: should find 4-card NaiveBomb to beat a Single": ["3S","3C","3D","3H"],
  "findMinBomb: should find the smallest NaiveBomb among multiple options": ["3S","3C","3D","3H"],
  "findMinBomb: should find bigger NaiveBomb to beat smaller NaiveBomb": ["7S","7C","7D","7H"],
  "findMinBomb: should return null when no bomb can beat prev bomb": null,
  "findMinBomb: should find StraightFlush to beat a smaller bomb": ["3S","4S","5S","6S","7S"],
  "findMinBomb: should find JokerBomb to beat a big bomb": ["SJ","SJ","BJ","BJ"],
  "findMinBomb: should find NaiveBomb with wildcard to beat a smaller bomb": ["3S","3C","3H","5H"],
  "findMinBomb: should prefer smaller bomb over larger bomb when beating a bomb": ["3S","3C","3D","3H"],
  "findMinBomb 27cards: 场景1 prev = 4个9": ["10C","10H","5H","5H"],
  "findMinBomb 27cards: 场景2 prev = 5个10": ["KS","KC","KC","KH","5H"],
  "findMinBomb 27cards: 场景3 prev = 6个5": ["SJ","SJ","BJ","BJ"],
  "findMinBomb 27cards: 场景4 prev = 7个6": ["SJ","SJ","BJ","BJ"],
  "findMinBomb 27cards: 场景5 prev = 8个2": ["SJ","SJ","BJ","BJ"],
  "findMinBomb 27cards: 场景6 prev = Heart 3,4,5,6,7": ["4S","6S","7S","8S","5H"],
  "findMinBomb 27cards: 场景7 prev = Club 5,6,7,8,9": ["6S","7S","8S","5H","5H"],
  "Single: should find smallest single to beat prev single": ["7S"],
  "Single: should return null when no single can beat prev": null,
  "Single: should use wildcard as single": ["5H"],
  "Pair: should find smallest pair to beat prev pair": ["7S","7H"],
  "Pair: should find pair with wildcard": ["7S","5H"],
  "Pair: should return null when no pair can beat prev": null,
  "Triple: should find smallest triple to beat prev triple": ["8S","8C","8H"],
  "Triple: should find triple with wildcard": ["8S","8H","5H"],
  "Triple: should use pure wildcards as triple": ["5H","5H","5H"],
  "Single 27cards: 场景1 prev = 单张黑桃3": ["4S"],
  "Single 27cards: 场景2 prev = 单张黑桃K": ["5H"],
  "Single 27cards: 场景3 prev = 单张A": ["5H"],
  "Single 27cards: 场景4 prev = 单张小王": ["BJ"],
  "Single 27cards: 场景5 prev = 单张大王": ["3S","3S","5H","5H"],
  "Single 27cards: 场景6 prev = 单张5 (级牌)": ["SJ"],
  "Pair 27cards: 场景1 prev = 对3": ["4S","4S"],
  "Pair 27cards: 场景2 prev = 对8": ["9C","9H"],
  "Pair 27cards: 场景3 prev = 对K": ["5H","5H"],
  "Pair 27cards: 场景4 prev = 对小王": ["BJ","BJ"],
  "Pair 27cards: 场景5 prev = 对大王": ["3S","3S","5H","5H"],
  "Pair 27cards: 场景6 prev = 对5 (级牌)": ["SJ","SJ"],
  "Triple 27cards: 场景1 prev = 三张3": ["4S","4S","5H"],
  "Triple 27cards: 场景2 prev = 三张6": ["7S","7S","7H"],
  "Triple 27cards: 场景3 prev = 三张K": ["3S","3S","5H","5H"],
  "Triple 27cards: 场景4 prev = 三张8": ["9C","9H","5H"],
  "Straight: should find smallest straight to beat prev straight": ["3S","4S","5S","6S","7S"],
  "Straight: should find straight with wildcard": ["3S","4S","6S","7S","5H"],
  "Straight: should return null when no straight can beat prev": null,
  "Straight: should find straight 10-A": ["10S","JS","QS","KS","AS"],
  "Straight 27cards: 场景1 prev = 顺子 A-2-3-4-5": ["3S","4S","6S","7S","5H"],
  "Straight 27cards: 场景2 prev = 顺子 3-4-5-6-7": ["4S","6S","7S","8S","5H"],
  "Straight 27cards: 场景3 prev = 顺子 5-6-7-8-9": ["6S","7S","8S","9H","10H"],
  "Straight 27cards: 场景4 prev = 顺子 6-7-8-9-10": ["7S","8S","9H","10H","5H"],
  "Straight 27cards: 场景5 prev = 顺子 10-J-Q-K-A": ["3S","3S","5H","5H"],
  "Tube: should find smallest tube to beat prev tube": ["3S","3H","4S","4H","5S","5H"],
  "Tube: should find tube with wildcard": ["5H","5H","3S","3H","4S","4H"],
  "Tube: should return null when no tube can beat prev": null,
  "Tube: should find tube QKA": ["QS","QH","KS","KH","AS","AH"],
  "FullHouse 27cards: 场景1 prev = 333+44": ["4S","4S","5H","3S","3S"],
  "FullHouse 27cards: 场景2 prev = 666+33": ["7S","7S","7H","3S","3S"],
  "FullHouse 27cards: 场景3 prev = 777+33": ["8S","8C","8H","3S","3S"],
  "FullHouse 27cards: 场景4 prev = 888+44": ["9C","9H","5H","3S","3S"],
  "FullHouse 27cards: 场景5 prev = 777+AA": ["8S","8C","8H","3S","3S"],
  "FullHouse 27cards: 场景6 prev = 888+大王对": ["9C","9H","5H","3S","3S"],
  "FullHouse 27cards: 场景7 prev = KKK+大王对": ["3S","3S","5H","5H"],
  "FullHouse 27cards: 场景8 prev = 999+1010": ["10C","10H","5H","3S","3S"],
};
